### ISSUE TITLE
Unable to connect to server with nginx authentication configured

### ISSUE THREAD

**Issue by kkuhle** [BlitterStudio/MB_SubSonic#24] opened 2017-04-12 18:48 UTC
I am trying to get musicbee to connect to my libresonic server with this plugin.  When I hit apply, I get the error message that the server did not respond as expected.

I have tried http://your-server/rest/ping.view?u=joe&p=sesame&v=1.12.0&c=myapp which comes back with "<subsonic-response xmlns="http://libresonic.org/restapi" status="ok" version="1.13.0"/>"

When I click "No" to the save anyway prompt it shows "Error: There is an error in XML document (1,2).

I am using a docker libresonic which is behind an nginx reverse proxy.  I was able to get this working locally.

**Comment by kkuhle** [comment] 2017-04-12 19:39
@weirdcrap I was looking at the enhancement that @midwan fulfilled to make libresonic compatible with his plugin.  I am also using the linuxserver io docker behind nginx.  Perhaps there is something wrong with my config since I'm finding it will work locally.  Do you use a context_path such as libresonic?  Would you be willing to share your config that you're using in your sites file for libresonic?

**Comment by midwan** [comment] 2017-04-12 20:21
@kkuhle 
I've recently installed a libresonic server here, which is also using Docker (on a FreeNAS 10 machine), so I can easily test it locally and see.

The recent update added support for Libresonic responses, so using the latest version should work with it without problems (before that you would get the invalid response from server message).

Could you verify you're using the latest version please?

**Comment by weirdcrap** [comment] 2017-04-12 20:33
@kkuhle 

This is the relevant section from my nginx reverse proxy configuration:
## LibreSonic Server ##
server {
        listen 80;
        server_name libresonic.yourdomain.com;
         location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass      http://xxx.xxx.xxx.xxx:4040;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   Host      $http_host;
        }
}

**Comment by midwan** [comment] 2017-04-12 20:36
@weirdcrap Thanks for sharing :)

Meanwhile, I just confirmed that the plugin works with my LibreSonic installation locally. Tomorrow I can try a remote connection also, just in case. If that seems to work as well, and @kkuhle still can't connect, perhaps we can look into the specifics of that environment.

**Comment by kkuhle** [comment] 2017-04-12 20:54
@midwan My version says "6.1 – April 7, 2017"

@weirdcrap Thanks.  I am using SSL for libresonic, so perhaps this is causing an issue.  As I said before, locally it is working, but it does http locally.  I will reconfigure nginx to use http to see if it works that way.

**Comment by midwan** [comment] 2017-04-12 20:56
@kkuhle 
I was referring to the plugin version, it should be at least v2.10:
![image](https://cloud.githubusercontent.com/assets/3877365/24979069/3262db86-1fd3-11e7-9dd0-a29b39f7454a.png)

**Comment by kkuhle** [comment] 2017-04-12 20:59
@midwan My mistake.  It should be 2.10 however the plugin does say 

![image](https://cloud.githubusercontent.com/assets/11251306/24979150/66800576-1f90-11e7-9505-249dea3cfb23.png)

I downloaded the 2.10 beta version and the file name is MB_SubSonic_v2.10beta.7z

**Comment by midwan** [comment] 2017-04-12 21:02
@kkuhle 
Ok then - I forgot that the version shows in the latest version only ;)
If you're on v2.10 then it should work.

The only change in v2.11 is the status display (it will show relevant messages while scanning a folder), I was waiting for some feedback from Steven to fix another item before releasing it.

**Comment by kkuhle** [comment] 2017-04-12 21:15
@midwan 
It is working!  I switched my config to do http rather than https in nginx for libresonic.  So for some reason https is breaking it.  I don't mind using http for this site though.

**Comment by midwan** [comment] 2017-04-12 21:17
@kkuhle 
Great news! Do you have a valid certificate for HTTPS? If not, maybe that's causing an issue.

Generally the plugin does work with HTTPS connections as well...

**Comment by kkuhle** [comment] 2017-04-12 22:16
So I set libresonic up a while back.  My nginx is using a valid ssl certificate from letsencrypt.  It works great on all of my other websites.  With libresonic however it looks like this

**Comment by weirdcrap** [comment] 2017-04-12 23:50
I believe what it is doing is hiding all elements that are not "secure" until you actively allow them. So it seems like the issue is that some parts of your libresonic interface are not being transmitted securely and your browser is hiding them.

As for any configuration you may need to make in the docker, you should probably post on the linux.io forum.

**Comment by kkuhle** [comment] 2017-04-13 00:54
@weirdcrap

I agree with you that I should talk to linuxserver.io about it. I've just never been too concerned about it since everything I need works fine. Might still ask them about it though.

**Comment by kkuhle** [comment] 2017-04-13 02:13
@midwan

So I was thinking about this earlier and just got a chance to test it.  I am using basic auth for my https sites in nginx. I just turned it off for libresonic and it works normally with https.

I think I didn't consider this is because I use dsub on my Android which works fine. What I have done is configured an nginx auth user with the same credentials as my libresonic user and it connects to the server normally.

Maybe the plugin can be modified to allow something like this?

**Comment by kkuhle** [comment] 2017-04-18 16:29
@midwan 

I went ahead and updated the title of this bug since the issue for me seemed to be occurring because nginx auth was set up.  Now that I've got it working with nginx auth turned off, I can live with it.  However it would be nice to use nginx auth again as I prefer having it on as I've configured fail2ban to block IPs and it is unable to do this with the basic auth turned off.

If it would help, I can set up a user for you to test with.

No rush, but if this can be looked at, that would be cool.

**Comment by jomant** [comment] 2017-05-01 02:56
I have a valid HTTPS certificate, runs website, TeamSpeak3 Subsonic Server (freeNAS), Nextcloud, Space Engineers Servers. Got 2 Dell Power Edge and a Intel....whatever 12 Bay NAS. I can access the Subsonic Server remotely via SoundWave, E Sub and the Web player without any issues.  I changed the Port from 80 to 443 (for HTTPS) still nothing. The database is approx. 120 GB big..... any guess how long this could take? Or any kind of other way to see even if the sync process starts?

**Comment by midwan** [comment] 2017-05-01 11:31
@jomant 
The latest version of the plugin displays a status update during scanning in MusicBee (at the bottom left)

**Comment by midwan** [comment] 2021-02-05 19:29
Please test with the latest release: https://github.com/midwan/MB_SubSonic/releases/tag/v2.30

The problematic pre-caching is removed, and files/folders are only loaded on-demand now. Hopefully that should make it work better for you?

**Comment by midwan** [comment] 2022-11-06 15:21
Closing this as there hasn't been any activity for quite a while now.

**Closed by midwan** 2022-11-06 15:21 UTC
Labels: enhancement
